name: GreyscaleTheatre
favicon: null
layout_spectrum: 0.34687759145163
typography_spectrum: 0.94675
title: Greyscale Theatre
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#4f4f4f'
    - '#757575'
    - '#cacaca'
  brandStrength: 0.3125
  lightness: 0.26219211844727397
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
